#!/bin/sh
#Selection=true
Environment=wayland
source /etc/profile.d/flatpak.sh
#export XDG_CURRENT_DESKTOP=river
#export SDL_VIDEODRIVER=wayland
#export _JAVA_AWT_WM_NONREPARENTING=1
#export QT_QPA_PLATFORM=wayland
#export XDG_CURRENT_DESKTOP=sway
#export XDG_SESSION_DESKTOP=sway
#systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
#exec dbus-launch $@
#exec dbus-launch river
#dbus-run-session river
#XDG_CURRENT_DESKTOP=sway dbus-run-session river
#river
Hyprland
