{ pkgs, inputs, ... }: {  
  environment.systemPackages = with pkgs; [
    wget
    kitty
    wezterm
    lutris
    gnome.gnome-software
    gnome.gnome-tweaks
    gnome.nautilus
    gnome.sushi
    gnome.gnome-disk-utility
    gnome.gnome-system-monitor
    gnome.gnome-boxes
    networkmanagerapplet
    #nautilus-open-any-terminal
    #gnome.nautilus-python
    #steamtinkerlaunch
        yad
        unixtools.xxd
        xorg.xwininfo
        unzip
        xdotool
        xorg.xprop
    goverlay
    vkbasalt
    mangohud
    replay-sorcery
    font-manager
    nerdfonts
    pavucontrol
    waylock
    libva
    xdg-utils
    libsForQt5.polkit-kde-agent
    libsForQt5.qt5.qtwayland
    libsForQt5.qt5ct
    inputs.nix-software-center.packages.${system}.nix-software-center
    inputs.hyprpicker.packages.${system}.hyprpicker
    inputs.ags.packages.${system}.default
    #inputs.ollama-nix.packages.${system}.default
    wineWowPackages.stable
    sunshine
    swayosd
    distrobox
    #sass
    #sassc
    clevis
    tpm-tools
    sbctl
    pinentry-qt
    dart-sass
    gtk3
    #gtk4
    #pango
    #pangomm
    #pixman
    fd
    corefonts
  ];
}
